export let TRIPS = [
  {
    id: 1,
    name: "Doi suthep",
    price_adult: 10,
    price_child: 5,
    time: "12h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/imgs/trip/thumb/Doisuthep2-800x534.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [
      "assets/imgs/trip/thumb/Doisuthep2-800x534.jpg",
      "assets/imgs/trip/thumb/trip_5.jpg",
      "assets/imgs/trip/thumb/trip_6.jpg",
      "assets/imgs/trip/thumb/trip_7.jpg",
      "assets/imgs/trip/thumb/trip_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 2,
    name: "Chiang mai night safari",
    price_adult: 33,
    price_child: 15,
    time: "4h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/imgs/trip/thumb/Travel_2.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [],
    highlights: []
  },
  {
    id: 3,
    name: "Ipiranga Museum",
    price_adult: 30,
    price_child: 15,
    time: "6h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/imgs/trip/thumb/trip_3.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "São Paulo, Brazil",
    images: [],
    highlights: []
  },
  {
    id: 4,
    name: "Fernando de Noronha",
    price_adult: 500,
    price_child: 250,
    time: "24h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/imgs/trip/thumb/trip_4.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [],
    highlights: []
  }
]
